approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nmMode: hardlinks-local

nmSelfReferences: false

nodeLinker: node-modules

npmMinimalAgeGate: 0
